// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MovingController from "./moving_controller"
application.register("moving", MovingController)

import PictureController from "./picture_controller"
application.register("picture", PictureController)

import SwitchingController from "./switching_controller"
application.register("switching", SwitchingController)
